
package com.inventory.UI;

import com.inventory.DAO.UserDAO;
import com.inventory.DTO.UserDTO;
import com.inventory.Database.ConnectionFactory;

import javax.swing.*;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDateTime;



public class Dashboard extends javax.swing.JFrame {

    CardLayout layout;
    String userSelect;
    String username;
    String fullName;
    UserDTO userDTO;
    LocalDateTime outTime;
    /**
     * Creates new form Dashboard
     */
    public Dashboard(String username, String userType, UserDTO userDTO) {
        initComponents();
        setLocationRelativeTo(this);
        navPanel.setVisible(false);
        //menuPanel.setVisible(true);
        layout = new CardLayout();
        userSelect = userType;
        this.username = username;
        this.userDTO = userDTO;
        if("EMPLOYEE".equalsIgnoreCase(userType))
            notForEmployee();
        currentUserSession();

        displayPanel.setLayout(layout);
        displayPanel.add("Home", new HomePage(username));
        displayPanel.add("Users", new PaginaUsers());
        displayPanel.add("Customers", new PaginaClientes());
        displayPanel.add("Products", new PaginaProductos(username, this));
        displayPanel.add("Suppliers", new PaginaProveedores());
        displayPanel.add("Current Stock", new PaginaStockActual(username));
        displayPanel.add("Sales", new PaginaVentas(username, this));
        displayPanel.add("Purchase", new PaginaCompras(this));
        displayPanel.add("Logs", new PaginaUserLogs());

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                outTime = LocalDateTime.now();
                userDTO.setOutTime(String.valueOf(outTime));
                userDTO.setUsername(username);
                new UserDAO().addUserLogin(userDTO);
                super.windowClosing(e);
            }
        });

        setTitle("Sistema de Gestión de Inventarios");
        setVisible(true);
    }

    // Methods to display different sections in the mainframe
    public void addHomePage(){
        layout.show(displayPanel, "Home");
    }
    public void addUsersPage() {
        layout.show(displayPanel, "Users");
    }
    public void addCustPage() {
        layout.show(displayPanel, "Customers");
    }
    public void addProdPage() {
        layout.show(displayPanel, "Products");
    }
    public void addSuppPage() {
        layout.show(displayPanel, "Suppliers");
    }
    public void addStockPage() {
        layout.show(displayPanel, "Current Stock");
    }
    public void addSalesPage() {
        layout.show(displayPanel, "Sales");
    }
    public void addPurchasePage() {
        layout.show(displayPanel, "Purchase");
    }
    public void addLogsPage() {
        layout.show(displayPanel, "Logs");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        navPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        prodButton = new javax.swing.JButton();
        stockButton = new javax.swing.JButton();
        custButton = new javax.swing.JButton();
        suppButton = new javax.swing.JButton();
        salesButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        purchaseButton = new javax.swing.JButton();
        logsButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        menuButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory Manager");
        setBounds(new java.awt.Rectangle(400, 100, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1061, 652));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        navPanel.setOpaque(false);
        navPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER LOGS");
        navPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 90, 40));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/homepages_home_house_icon_150665.png"))); // NOI18N
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        navPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 35));

        prodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/ButtonIcons/products.png"))); // NOI18N
        prodButton.setBorderPainted(false);
        prodButton.setContentAreaFilled(false);
        prodButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButtonActionPerformed(evt);
            }
        });
        navPanel.add(prodButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 50));

        stockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/ButtonIcons/currentstock.png"))); // NOI18N
        stockButton.setContentAreaFilled(false);
        stockButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockButtonActionPerformed(evt);
            }
        });
        navPanel.add(stockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 98, 50));

        custButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/ButtonIcons/customers.png"))); // NOI18N
        custButton.setContentAreaFilled(false);
        custButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        custButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custButtonActionPerformed(evt);
            }
        });
        navPanel.add(custButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 98, 50));

        suppButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/ButtonIcons/suppliers.png"))); // NOI18N
        suppButton.setContentAreaFilled(false);
        suppButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppButtonActionPerformed(evt);
            }
        });
        navPanel.add(suppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 98, 50));

        salesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/ButtonIcons/sales.png"))); // NOI18N
        salesButton.setContentAreaFilled(false);
        salesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesButtonActionPerformed(evt);
            }
        });
        navPanel.add(salesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 98, 50));

        usersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/ButtonIcons/users.png"))); // NOI18N
        usersButton.setContentAreaFilled(false);
        usersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersButtonActionPerformed(evt);
            }
        });
        navPanel.add(usersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 98, 50));

        purchaseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/ButtonIcons/purchase.png"))); // NOI18N
        purchaseButton.setContentAreaFilled(false);
        purchaseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });
        navPanel.add(purchaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 98, 50));

        logsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/ButtonIcons/userlogs.png"))); // NOI18N
        logsButton.setContentAreaFilled(false);
        logsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsButtonActionPerformed(evt);
            }
        });
        navPanel.add(logsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 100, 50));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRODUCTOS");
        navPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, 40));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STOCK ACTUAL");
        navPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, 40));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CLIENTES");
        navPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 90, 40));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PROVEEDORES");
        navPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 90, 40));

        jLabel7.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VENTAS");
        navPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 90, 40));

        jLabel8.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("COMPRAS");
        navPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 90, 40));

        jLabel9.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USUARIOS");
        navPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 90, 40));

        mainPanel.add(navPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, -1));

        displayPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(displayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 830, 590));

        menuButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/menu_icon_150667.png"))); // NOI18N
        menuButton.setText("MENU");
        menuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        mainPanel.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/background.jpg"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 690));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/logoversion2.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        mainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 4, 280, 50));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/UI/Icons/ButtonIcons/logout2.png"))); // NOI18N
        logoutButton.setContentAreaFilled(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        mainPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 70, 40));

        nameLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(204, 0, 102));
        nameLabel.setText("USUARIO:");
        mainPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 190, 20));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButtonActionPerformed
        addUsersPage();
    }//GEN-LAST:event_usersButtonActionPerformed

    private void salesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesButtonActionPerformed
        addSalesPage();
    }//GEN-LAST:event_salesButtonActionPerformed

    private void suppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppButtonActionPerformed
        addSuppPage();
    }//GEN-LAST:event_suppButtonActionPerformed

    private void custButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custButtonActionPerformed
        addCustPage();
    }//GEN-LAST:event_custButtonActionPerformed

    private void stockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockButtonActionPerformed
        addStockPage();
    }//GEN-LAST:event_stockButtonActionPerformed

    private void prodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButtonActionPerformed
        addProdPage();
    }//GEN-LAST:event_prodButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        //dispose();
        addHomePage();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        navPanel.setVisible(!navPanel.isVisible());
    }//GEN-LAST:event_menuButtonActionPerformed

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        addPurchasePage();
    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void logsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsButtonActionPerformed
        addLogsPage();
    }//GEN-LAST:event_logsButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int opt = JOptionPane.showConfirmDialog(
            null,
            "<html>¿Seguro que quiere salir?<br>Deberá iniciar sesion de nuevo.<html>",
            "Confirmation",
            JOptionPane.YES_NO_OPTION);
        if (opt==JOptionPane.YES_OPTION){
            outTime = LocalDateTime.now();
            userDTO.setOutTime(String.valueOf(outTime));
            userDTO.setUsername(username);
            new UserDAO().addUserLogin(userDTO);
            dispose();
            PaginaLogin logPage = new PaginaLogin();
            logPage.setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

   
    //Metodo para desplegar el usuario que esta logeado
    public void currentUserSession() {
        UserDTO userDTO = new UserDTO();
        new UserDAO().getFullName(userDTO, username);
        nameLabel.setText("User: " + userDTO.getFullName() + " ("+userSelect+")");
    }

    //Metodo para visualizar 'User' y 'UserLogs' solo para administradores.
    public void notForEmployee(){
        navPanel.remove(usersButton);
        navPanel.remove(logsButton);
        //navPanel.remove(salesButton);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton custButton;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton logsButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JButton prodButton;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JButton salesButton;
    private javax.swing.JButton stockButton;
    private javax.swing.JButton suppButton;
    private javax.swing.JButton usersButton;
    // End of variables declaration//GEN-END:variables
}
