/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diseñoalex;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class paginaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form paginaUsuarios
     */
    public paginaUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu2 = new javax.swing.JPanel();
        labelMenu2 = new javax.swing.JLabel();
        botonInicio2 = new javax.swing.JButton();
        botonProductos2 = new javax.swing.JButton();
        botonProveedores2 = new javax.swing.JButton();
        botonClientes2 = new javax.swing.JButton();
        botonCompras2 = new javax.swing.JButton();
        botonRegistroDeUsuarios2 = new javax.swing.JButton();
        botonUsuarios2 = new javax.swing.JButton();
        botonVentas2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        panelDatosProveedor4 = new javax.swing.JPanel();
        labelUbicacion4 = new javax.swing.JLabel();
        labelNombreCompleto4 = new javax.swing.JLabel();
        labelContraseña4 = new javax.swing.JLabel();
        labelNombreDeUsuario4 = new javax.swing.JLabel();
        labelContacto4 = new javax.swing.JLabel();
        textoNombreCompleto4 = new javax.swing.JTextField();
        textoContacto4 = new javax.swing.JTextField();
        textoUbicacion4 = new javax.swing.JTextField();
        textoNombreDeUsuario4 = new javax.swing.JTextField();
        botonAgregar4 = new javax.swing.JButton();
        botonEliminar4 = new javax.swing.JButton();
        botonLimpiar4 = new javax.swing.JButton();
        textoContraseña4 = new javax.swing.JPasswordField();
        comboBoxTipoDeUsuario = new javax.swing.JComboBox<>();
        labelUsuarios = new javax.swing.JLabel();
        panelBuscar2 = new javax.swing.JPanel();
        botonSalir2 = new javax.swing.JButton();
        labelUsuario2 = new javax.swing.JLabel();
        labelNombreDeUsuario2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu_icon_150667.png"))); // NOI18N
        labelMenu2.setText("MENU");
        labelMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonInicio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonInicio2.setText("Inicio");
        botonInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicio2ActionPerformed(evt);
            }
        });

        botonProductos2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonProductos2.setText("Productos");
        botonProductos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductos2ActionPerformed(evt);
            }
        });

        botonProveedores2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonProveedores2.setText("Proveedores");
        botonProveedores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProveedores2ActionPerformed(evt);
            }
        });

        botonClientes2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonClientes2.setText("Clientes");
        botonClientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientes2ActionPerformed(evt);
            }
        });

        botonCompras2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCompras2.setText("Compras");
        botonCompras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompras2ActionPerformed(evt);
            }
        });

        botonRegistroDeUsuarios2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistroDeUsuarios2.setText("Registro de Usuarios");
        botonRegistroDeUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroDeUsuarios2ActionPerformed(evt);
            }
        });

        botonUsuarios2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonUsuarios2.setText("Usuarios");
        botonUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarios2ActionPerformed(evt);
            }
        });

        botonVentas2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonVentas2.setText("Ventas");
        botonVentas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentas2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu2Layout = new javax.swing.GroupLayout(panelMenu2);
        panelMenu2.setLayout(panelMenu2Layout);
        panelMenu2Layout.setHorizontalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonInicio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonProductos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonClientes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonUsuarios2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRegistroDeUsuarios2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVentas2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCompras2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonProveedores2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenu2Layout.setVerticalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(botonInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonClientes2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonProveedores2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVentas2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCompras2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistroDeUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "UBICACIÓN", "TELÉFONO", "NOMBRE DE USUARIO", "CONTRASEÑA", "TIPO DE USUARIO"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        panelDatosProveedor4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los datos del usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        labelUbicacion4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUbicacion4.setText("Ubicación");

        labelNombreCompleto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreCompleto4.setText("Nombre Completo");

        labelContraseña4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContraseña4.setText("Contraseña");

        labelNombreDeUsuario4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreDeUsuario4.setText("Nombre de Usuario");

        labelContacto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContacto4.setText("Contacto");

        textoNombreCompleto4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoNombreCompleto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoContacto4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoContacto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoUbicacion4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoUbicacion4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoNombreDeUsuario4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoNombreDeUsuario4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonAgregar4.setText("Agregar");
        botonAgregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar4ActionPerformed(evt);
            }
        });

        botonEliminar4.setText("Eliminar");
        botonEliminar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminar4ActionPerformed(evt);
            }
        });

        botonLimpiar4.setText("Limpiar");
        botonLimpiar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiar4ActionPerformed(evt);
            }
        });

        textoContraseña4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textoContraseña4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoContraseña4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboBoxTipoDeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de usuario", "Administrador", "Empleado" }));

        javax.swing.GroupLayout panelDatosProveedor4Layout = new javax.swing.GroupLayout(panelDatosProveedor4);
        panelDatosProveedor4.setLayout(panelDatosProveedor4Layout);
        panelDatosProveedor4Layout.setHorizontalGroup(
            panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosProveedor4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxTipoDeUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatosProveedor4Layout.createSequentialGroup()
                        .addGroup(panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUbicacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelContacto4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombreCompleto4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNombreCompleto4)
                            .addComponent(textoContacto4)
                            .addComponent(textoUbicacion4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelDatosProveedor4Layout.createSequentialGroup()
                        .addComponent(labelNombreDeUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNombreDeUsuario4))
                    .addGroup(panelDatosProveedor4Layout.createSequentialGroup()
                        .addComponent(labelContraseña4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoContraseña4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosProveedor4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAgregar4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminar4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonLimpiar4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDatosProveedor4Layout.setVerticalGroup(
            panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosProveedor4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreCompleto4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombreCompleto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUbicacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoUbicacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContacto4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoContacto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreDeUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombreDeUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContraseña4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoContraseña4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxTipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDatosProveedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar4)
                    .addComponent(botonLimpiar4)
                    .addComponent(botonAgregar4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        labelUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuarios.setText("USUARIOS");

        botonSalir2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/log-out_icon-icons.com_50106.png"))); // NOI18N
        botonSalir2.setText("Salir");

        labelUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user_icon_150670.png"))); // NOI18N
        labelUsuario2.setText("Usuario");

        labelNombreDeUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNombreDeUsuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreDeUsuario2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelBuscar2Layout = new javax.swing.GroupLayout(panelBuscar2);
        panelBuscar2.setLayout(panelBuscar2Layout);
        panelBuscar2Layout.setHorizontalGroup(
            panelBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(labelNombreDeUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBuscar2Layout.setVerticalGroup(
            panelBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNombreDeUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDatosProveedor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(labelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDatosProveedor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInicio2ActionPerformed

    private void botonProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProductos2ActionPerformed

    private void botonProveedores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProveedores2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProveedores2ActionPerformed

    private void botonClientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonClientes2ActionPerformed

    private void botonCompras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompras2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCompras2ActionPerformed

    private void botonRegistroDeUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroDeUsuarios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroDeUsuarios2ActionPerformed

    private void botonUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonUsuarios2ActionPerformed

    private void botonVentas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVentas2ActionPerformed

    private void botonAgregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar4ActionPerformed
    UserDTO user DTO = new UserDTO();
        if (textoNombreCompleto4.getText().equals("")||textoUbicacion4.getText().equals("")||
                textoContacto4.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Rellenar todos los campos requeridos");
        }else{
            userType=(String)comboBoxTipoDeUsuario.getSelectedItem();
            userDTO.setFullName(textoNombreCompleto4.getText());
            userDTO.setLocation(textoUbicacion4.getText());
            userDTO.setPhone(textoContacto4.getText());
            userDTO.setUsername(textoNombreDeUsuario4.getText());
            userDTO.setPassword(textoContraseña4.getText());
            userDTO.setUsertype(userType);
            new UserDAO().addUserDAO(userDTO,userType);
            loadDataSet();
        }
    }//GEN-LAST:event_botonAgregar4ActionPerformed

    private void botonLimpiar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiar4ActionPerformed
    textoNombreCompleto4.setText("");
    textoUbicacion4.setText("");
    textoContacto4.setText("");
    textoNombreDeUsuario4.setText("");
    textoContraseña4.setText("");
    }//GEN-LAST:event_botonLimpiar4ActionPerformed

    private void botonEliminar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminar4ActionPerformed
        if (tablaUsuarios.getSelectedRow()<0) {
            JOptionPane.showConfirmDialog(null, "Seleccione una entrada de la tabla");
        }else{
            int opt=JOptionPane.showConfirmDialog(null, "¿Seguro de eliminar a este usuario?"
                    , "Confirmacion",JOptionPane.YES_NO_OPTION);
            if (opt==JOptionPane.YES_OPTION) {
                new UserDAO().deleteUserDAO(String.valueOf(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(),4)));
                loadDataSet();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar4;
    private javax.swing.JButton botonClientes2;
    private javax.swing.JButton botonCompras2;
    private javax.swing.JButton botonEliminar4;
    private javax.swing.JButton botonInicio2;
    private javax.swing.JButton botonLimpiar4;
    private javax.swing.JButton botonProductos2;
    private javax.swing.JButton botonProveedores2;
    private javax.swing.JButton botonRegistroDeUsuarios2;
    private javax.swing.JButton botonSalir2;
    private javax.swing.JButton botonUsuarios2;
    private javax.swing.JButton botonVentas2;
    private javax.swing.JComboBox<String> comboBoxTipoDeUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelContacto4;
    private javax.swing.JLabel labelContraseña4;
    private javax.swing.JLabel labelMenu2;
    private javax.swing.JLabel labelNombreCompleto4;
    private javax.swing.JLabel labelNombreDeUsuario2;
    private javax.swing.JLabel labelNombreDeUsuario4;
    private javax.swing.JLabel labelUbicacion4;
    private javax.swing.JLabel labelUsuario2;
    private javax.swing.JLabel labelUsuarios;
    private javax.swing.JPanel panelBuscar2;
    private javax.swing.JPanel panelDatosProveedor4;
    private javax.swing.JPanel panelMenu2;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField textoContacto4;
    private javax.swing.JPasswordField textoContraseña4;
    private javax.swing.JTextField textoNombreCompleto4;
    private javax.swing.JTextField textoNombreDeUsuario4;
    private javax.swing.JTextField textoUbicacion4;
    // End of variables declaration//GEN-END:variables
}
