/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diseñoalex;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class paginaLogUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form paginaLogUsuarios
     */
    public paginaLogUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistroDeUsuarios = new javax.swing.JTable();
        labelRegistroDeUsuarios = new javax.swing.JLabel();
        panelMenu2 = new javax.swing.JPanel();
        labelMenu2 = new javax.swing.JLabel();
        botonInicio2 = new javax.swing.JButton();
        botonProductos2 = new javax.swing.JButton();
        botonProveedores2 = new javax.swing.JButton();
        botonClientes2 = new javax.swing.JButton();
        botonCompras2 = new javax.swing.JButton();
        botonRegistroDeUsuarios2 = new javax.swing.JButton();
        botonUsuarios2 = new javax.swing.JButton();
        botonVentas2 = new javax.swing.JButton();
        panelBuscar1 = new javax.swing.JPanel();
        labelBuscar1 = new javax.swing.JLabel();
        textoBuscar1 = new javax.swing.JTextField();
        botonSalir1 = new javax.swing.JButton();
        labelUsuario1 = new javax.swing.JLabel();
        labelNombreDeUsuario1 = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaRegistroDeUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "NOMBRE DE USUARIO", "HORA DE CONEXIÓN", "HORA DE DESCONEXIÓN", "UBICACIÓN"
            }
        ));
        jScrollPane1.setViewportView(tablaRegistroDeUsuarios);

        labelRegistroDeUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelRegistroDeUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistroDeUsuarios.setText("REGISTRO DE USUARIOS");

        labelMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu_icon_150667.png"))); // NOI18N
        labelMenu2.setText("MENU");
        labelMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonInicio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonInicio2.setText("Inicio");
        botonInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicio2ActionPerformed(evt);
            }
        });

        botonProductos2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonProductos2.setText("Productos");
        botonProductos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductos2ActionPerformed(evt);
            }
        });

        botonProveedores2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonProveedores2.setText("Proveedores");
        botonProveedores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProveedores2ActionPerformed(evt);
            }
        });

        botonClientes2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonClientes2.setText("Clientes");
        botonClientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientes2ActionPerformed(evt);
            }
        });

        botonCompras2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCompras2.setText("Compras");
        botonCompras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompras2ActionPerformed(evt);
            }
        });

        botonRegistroDeUsuarios2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistroDeUsuarios2.setText("Registro de Usuarios");
        botonRegistroDeUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroDeUsuarios2ActionPerformed(evt);
            }
        });

        botonUsuarios2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonUsuarios2.setText("Usuarios");
        botonUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarios2ActionPerformed(evt);
            }
        });

        botonVentas2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonVentas2.setText("Ventas");
        botonVentas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentas2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu2Layout = new javax.swing.GroupLayout(panelMenu2);
        panelMenu2.setLayout(panelMenu2Layout);
        panelMenu2Layout.setHorizontalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu2Layout.createSequentialGroup()
                        .addComponent(labelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(panelMenu2Layout.createSequentialGroup()
                        .addGroup(panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonInicio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonProductos2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonClientes2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonUsuarios2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonRegistroDeUsuarios2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonVentas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCompras2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonProveedores2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelMenu2Layout.setVerticalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonClientes2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonProveedores2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVentas2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCompras2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistroDeUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        labelBuscar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelBuscar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscar1.setText("Buscar:");

        textoBuscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonSalir1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/log-out_icon-icons.com_50106.png"))); // NOI18N
        botonSalir1.setText("Salir");

        labelUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user_icon_150670.png"))); // NOI18N
        labelUsuario1.setText("Usuario");

        labelNombreDeUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNombreDeUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreDeUsuario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonActualizar.setText("ACTUALIZAR");
        botonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonEliminar.setText("ELIMINAR");
        botonEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscar1Layout = new javax.swing.GroupLayout(panelBuscar1);
        panelBuscar1.setLayout(panelBuscar1Layout);
        panelBuscar1Layout.setHorizontalGroup(
            panelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscar1Layout.createSequentialGroup()
                        .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelUsuario1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscar1Layout.createSequentialGroup()
                        .addComponent(labelNombreDeUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscar1Layout.createSequentialGroup()
                        .addComponent(textoBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBuscar1Layout.setVerticalGroup(
            panelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNombreDeUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoBuscar1)
                        .addComponent(labelBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRegistroDeUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(labelRegistroDeUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(panelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInicio2ActionPerformed

    private void botonProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProductos2ActionPerformed

    private void botonProveedores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProveedores2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProveedores2ActionPerformed

    private void botonClientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonClientes2ActionPerformed

    private void botonCompras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompras2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCompras2ActionPerformed

    private void botonRegistroDeUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroDeUsuarios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroDeUsuarios2ActionPerformed

    private void botonUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonUsuarios2ActionPerformed

    private void botonVentas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVentas2ActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
    loadDataSet();        
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        if (tablaRegistroDeUsuarios.getSelectedRow()<0) {
            JOptionPane.showMessageDialog(this, "Selecciona un Registro de Usuario de la tabla");
        }else{
            int opt=JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar este registro"
                    , "Confirmacion", JOptionPane.YES_NO_OPTION);
            if (opt==JOptionPane.YES_OPTION) {
                new UserDAO().deleteUserLogDao(tablaRegistroDeUsuarios.getValueAt(tablaRegistroDeUsuarios.getSelectedRow(), 2).toString());
                loadDataSet;
            }
        }
    
    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaLogUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaLogUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaLogUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaLogUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaLogUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonClientes2;
    private javax.swing.JButton botonCompras2;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonInicio2;
    private javax.swing.JButton botonProductos2;
    private javax.swing.JButton botonProveedores2;
    private javax.swing.JButton botonRegistroDeUsuarios2;
    private javax.swing.JButton botonSalir1;
    private javax.swing.JButton botonUsuarios2;
    private javax.swing.JButton botonVentas2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuscar1;
    private javax.swing.JLabel labelMenu2;
    private javax.swing.JLabel labelNombreDeUsuario1;
    private javax.swing.JLabel labelRegistroDeUsuarios;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JPanel panelBuscar1;
    private javax.swing.JPanel panelMenu2;
    private javax.swing.JTable tablaRegistroDeUsuarios;
    private javax.swing.JTextField textoBuscar1;
    // End of variables declaration//GEN-END:variables
}
